--DYNAMIC TABLE CREATION


USE ROLE ACCOUNTADMIN ; 

CREATE OR REPLACE DATABASE SNOWFLAKE_DEMO;
CREATE OR REPLACE SCHEMA DEMO;


CREATE OR REPLACE TABLE CUSTOMER
(
ID INT,
NAME VARCHAR(100)
);


INSERT INTO CUSTOMER VALUES(3,'C'),(4,'D') ;

SELECT * FROM CUSTOMER ;

UPDATE CUSTOMER SET NAME='ABC' WHERE ID=3;


CREATE OR REPLACE DYNAMIC TABLE DYNAMIC_CUSTOMER
(
ID INT,
NAME VARCHAR(100)
)
TARGET_LAG = '2 MINUTES'
WAREHOUSE = 'COMPUTE_WH'
REFRESH_MODE = AUTO 

AS

SELECT ID,NAME FROM CUSTOMER ; 

SELECT * FROM DYNAMIC_CUSTOMER ;

ALTER DYNAMIC TABLE DYNAMIC_CUSTOMER RESUME;
ALTER DYNAMIC TABLE DYNAMIC_CUSTOMER SUSPEND;

SELECT
  name,
  data_timestamp,
  state,
  state_code,
  state_message
    FROM TABLE (INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY (NAME_PREFIX => 'SNOWFLAKE_DEMO.DEMO')) ORDER BY data_timestamp desc;

SELECT
  name,
  data_timestamp,
  state,
  state_code,
  state_message
FROM TABLE (INFORMATION_SCHEMA.DYNAMIC_TABLE_REFRESH_HISTORY (name => 'DYNAMIC_CUSTOMER')) ORDER BY data_timestamp desc;

--ICEBERG DYNAMIC TABLES



Re-run your query. Query results are cached for 24 hours.
Query Details
Query duration
327ms
Rows
5
Query ID
01bcb0ab-0001-0d9e-0000-000993025225
Databases
Worksheets
Search objects

Sorted by descending