
CREATE OR REPLACE PROCEDURE USP_GETCUSTOMERDATA(CUSTOMERID INT)
RETURNS VARCHAR
LANGUAGE SQL
AS
DECLARE 

SQLQUERY VARCHAR ; 

BEGIN
SQLQUERY := 'UPDATE CUSTOMER_SOURCE SET NAME =''AAA'' WHERE CUSTOMERID = ' || :CUSTOMERID ;

EXECUTE IMMEDIATE SQLQUERY ;

RETURN 'UPDATED SUCCESSFULLY' ;


END;


CALL USP_GETCUSTOMERDATA(2)


CREATE OR REPLACE PROCEDURE USP_GETCUSTOMERDATA1(CUSTOMERID INT)
RETURNS TABLE(CUSTOMERID INT,
NAME VARCHAR,
ADDRESS VARCHAR,
PHONENUMBER BIGINT)
LANGUAGE SQL
AS
DECLARE 

SQLQUERY VARCHAR ; 
QUERYOUTPUT RESULTSET ; 

BEGIN
SQLQUERY := 'SELECT * FROM CUSTOMER_SOURCE WHERE CUSTOMERID = ' || :CUSTOMERID ;

QUERYOUTPUT := (EXECUTE IMMEDIATE SQLQUERY) ;

RETURN TABLE(QUERYOUTPUT) ;

END;

INSERT INTO CUSTOMER_TABLE
SELECT * FROM TABLE(USP_GETCUSTOMERDATA1(2))

CALL USP_GETCUSTOMERDATA1(2) ;

SELECT * FROM CUSTOMER_SOURCE

CREATE TABLE CUSTOMER_TABLE
(

CUSTOMERID INT,
NAME VARCHAR,
ADDRESS VARCHAR,
PHONENUMBER BIGINT
) ;


SELECT * FROM CUSTOMER_TABLE ;





