SHOW STAGES;

CREATE OR REPLACE EXTERNAL TABLE CUSTOMERDATA
WITH 
LOCATION = @CUSTOMER_DATA/   --EXTERNAL STAGE NAME
AUTO_REFRESH = TRUE
FILE_FORMAT = (TYPE = CSV) ;

SELECT * FROM DIRECTORY(@CUSTOMER_DATA)
LIST @CUSTOMER_DATA;



SELECT * FROM CUSTOMERDATA ;



CREATE OR REPLACE STAGE FLIGHT_DATA
URL = 's3://sairamkanamarlapudi/Market_Data/'
STORAGE_INTEGRATION = S3_INT
FILE_FORMAT = (TYPE = CSV SKIP_HEADER = 1 ) ;


LIST @FLIGHT_DATA

SELECT $1 FROM @FLIGHT_DATA





CREATE OR REPLACE EXTERNAL TABLE FLIGHT_DATA
(
flightid string as (value:c1:: string),
state string as (value:c2:: string),
Country string as (value:c3:: string)
)
WITH 
LOCATION = @FLIGHT_DATA
AUTO_REFRESH = TRUE
FILE_FORMAT =(TYPE = csv skip_header =1)


SELECT $1,$2,$3 FROM @FLIGHT_DATA

DESCRIBE TABLE FLIGHT_DATA

SHOW EXTERNAL TABLES LIKE '%FLIGHT_DATA%'

SELECT * FROM TABLE(INFORMATION_SCHEMA.EXTERNAL_TABLE_FILES(TABLE_NAME => 'FLIGHT_DATA'))


SELECT count(1) FROM FLIGHT_DATA ;  --11924





