

CREATE OR REPLACE TEMP TABLE CUSTOMERDATA
(
VALUE STRING
);

INSERT INTO CUSTOMERDATA VALUES ('A,B,C,D,E,F') ;

SELECT A.VALUE::STRING AS VALUE FROM 
CUSTOMERDATA AS B,
LATERAL FLATTEN (INPUT => SPLIT(VALUE,',')) AS A

CREATE OR REPLACE TABLE CUSTOMER
(
ID INT,
LOCATION STRING
);

INSERT INTO CUSTOMER VALUES
(1,'HYD'),(1,'BNG'),(1,'CHENNAI'),(1,'PUNE')

SELECT * FROM CUSTOMER;


SELECT ID , LISTAGG(LOCATION,',') WITHIN GROUP (ORDER BY LOCATION) AS LOCATION

FROM CUSTOMER GROUP BY ID ;





CREATE OR REPLACE TABLE EMPLOYEE
(
EMPID INT,
NAME STRING,
SALARY FLOAT
);


INSERT INTO EMPLOYEE VALUES
(1	,'A',	100),
(2	,'B',	200),
(3	,'C',	100),
(4	,'D',	300),
(5	,'E',	200),
(6	,'F',	300),
(1	,'A',	200);



WITH CTE AS
(
SELECT EMPID,NAME, SALARY, LEAD(SALARY) OVER(PARTITION BY EMPID ORDER BY SALARY DESC ) AS VALUE,
ROW_NUMBER() OVER(PARTITION BY EMPID ORDER BY SALARY DESC) AS RN
FROM EMPLOYEE
ORDER BY EMPID
)

SELECT EMPID,NAME, VALUE AS PREVIOUSSALARY,SALARY AS CURRENTSALARY FROM CTE WHERE RN=1


SELECT EMPID,IFNULL(NAME,'SUBTOTAL') AS NAME ,SUM(SALARY) FROM EMPLOYEE GROUP BY ROLLUP(EMPID,NAME) 
ORDER BY EMPID


CREATE OR REPLACE TABLE POLICY
(
POLICYID INT,
LOCATION STRING,
PREMIUM FLOAT
);

INSERT INTO POLICY VALUES
('1',	'HYD',	2000),
('2',	'HYD',	4000),
('3',	'HYD',	4000),
('4',	'BNG',	6000),
('5',	'BNG',	4000),
('6',	'BNG',	5000),
('7',	'BNG',	7000),
('8',	'CHN',	9000),
('9',	'CHN',	3000),
('10',	'CHN',	2000);


SELECT LOCATION ,IFF(LOCATION IS NULL , 'GRAND TOTAL' , IFNULL(CAST(POLICYID AS STRING),'SUB TOTAL')) AS POLICYID,SUM(PREMIUM) FROM POLICY GROUP BY ROLLUP(LOCATION,POLICYID) ORDER BY LOCATION  ;



SELECT *, CASE WHEN LOCATION ='HYD' THEN 'HYDERABAD' 
               WHEN LOCATION ='BNG' THEN 'BANGULUR' 
               WHEN LOCATION ='CHN' THEN 'CHENNAI' END AS LOCATION 
FROM POLICY








