/*----------------D1_1 Hands-on----------------
1) Role-based access control (RBAC)
2) Discretionary access control (DAC)
3) Roles & Privileges
4) Privilege Inheritance
----------------------------------------------*/

USE ROLE ACCOUNTADMIN ; 


SHOW GRANTS TO ROLE ACCOUNTADMIN ;

SHOW GRANTS TO ROLE SYSADMIN;

SHOW GRANTS TO ROLE SECURITYADMIN ;

SHOW GRANTS TO ROLE USERADMIN ;


------ CREATE A DATABASE ,SCHEMA AND TABLE

USE ROLE SYSADMIN ;

CREATE DATABASE FILMS_DB;
CREATE SCHEMA FILMS_SCHEMA;

CREATE TABLE FILMS_SYSADMIN
(
  ID STRING, 
  TITLE STRING,  
  RELEASE_DATE DATE,
  RATING INT
);

-- CREATE CUSTOMER ROLE


USE ROLE SECURITYADMIN ;


CREATE ROLE ANALYST ;


GRANT USAGE ON DATABASE FILMS_DB TO ROLE ANALYST ;
GRANT USAGE ON SCHEMA  FILMS_DB.FILMS_SCHEMA TO ROLE ANALYST;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE ANALYST ;
GRANT USAGE , CREATE TABLE ON SCHEMA FILMS_DB.FILMS_SCHEMA TO ROLE ANALYST;


GRANT ROLE ANALYST TO ROLE SYSADMIN ; 


SHOW GRANTS TO ROLE ANALYST ;
SHOW GRANTS TO ROLE SYSADMIN ;

USE ROLE ANALYST ; 


USE SCHEMA FILMS_DB.FILMS_SCHEMA;

CREATE TABLE FILMS_ANALYST
(
  ID STRING, 
  TITLE STRING,  
  RELEASE_DATE DATE,
  RATING INT
);

USE ROLE ANALYST ;
SHOW TABLES;

USE ROLE SYSADMIN ; 
SHOW TABLES;

USE ROLE SECURITYADMIN ; 

GRANT USAGE ON FUTURE SCHEMAS IN DATABASE  FILMS_DB TO ROLE ANALYST ;

USE ROLE SYSADMIN ;

CREATE SCHEMA MUSIC_SCHEMA;

CREATE SCHEMA BOOKS_SCHEMA;

SHOW SCHEMAS ; 

USE ROLE ANALYST ;
SHOW SCHEMAS ;

USE ROLE SYSADMIN ;

CREATE TABLE FILMS_DATA
(
  ID STRING, 
  TITLE STRING,  
  RELEASE_DATE DATE,
  RATING INT
);


USE ROLE ANALYST ;
SHOW TABLES ;

SHOW GRANTS TO ROLE ANALYST ;


----CREATE USER AND ASSIGN THIS ROLE TO USER

USE ROLE USERADMIN ;

CREATE USER KUMAR 
PASSWORD ='TEMP'
DEFAULT_ROLE = ANALYST
DEFAULT_WAREHOUSE = 'COMPUTE_WH' MUST_CHANGE_PASSWORD=TRUE;

USE ROLE SECURITYADMIN;

SHOW USERS ;

GRANT ROLE ANALYST TO USER KUMAR ; 








