
-- USER STAGE

LIST @~ ;

--TABLE STAGE

CREATE OR REPLACE TABLE CUSTOMER_SATGE
(
CUSTOMERID INT,
NAME VARCHAR(100)
);

LIST @%CUSTOMER_SATGE ;


select * from CUSTOMER_SATGE ;

PUT 
file:///Users/Sairam_Kanamarlapudi/Desktop/SnowFlake/UserStage/L_CITY_MARKET_ID.csv
@~/MARKET

PUT 
file:///Users/Sairam_Kanamarlapudi/Desktop/SnowFlake/UserStage/L_CITY_MARKET_ID.csv
@%CUSTOMER_SATGE


SELECT $1,$2 FROM @~/MARKET;

SHOW STAGES;


CREATE OR REPLACE FILE FORMAT CSV_DATA
TYPE ='CSV'
SKIP_HEADER = 1
FIELD_DELIMITER =',' ;



CREATE OR REPLACE TABLE MARKET
(
CODE VARCHAR(1000),
DESCRIPTION VARCHAR(1000),
FILENAME VARCHAR(1000),
LOADATE DATETIME
);

COPY INTO MARKET(CODE ,
DESCRIPTION,
--FILENAME,
LOADATE)
FROM (SELECT $1,$2,CURRENT_TIMESTAMP() FROM @~/MARKET)
FILE_FORMAT = CSV_DATA;

SELECT * FROM MARKET;

TRUNCATE TABLE MARKET;



SELECT * FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(TABLE_NAME=>'FLIGHTDATA.FLIGHTDATA.MARKET',START_TIME => DATEADD(HOUR,-14,CURRENT_TIMESTAMP())));

