---CREATE A STORAGE INTEGRATION

CREATE OR REPLACE  STORAGE INTEGRATION S3_INT
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::484907489267:role/FlightData'
  ENABLED = TRUE 
  STORAGE_ALLOWED_LOCATIONS = ('s3://sairamkanamarlapudi')
 -- [ STORAGE_BLOCKED_LOCATIONS = ('<cloud>://<bucket>/<path>/' [ , '<cloud>://<bucket>/<path>/' ... ] ) ]
  COMMENT = 'STORAGE INTEGRATION FOR S3 BUCKET' 


SHOW INTEGRATIONS LIKE 'S3_INT';
  
---- CREATE A EXTERNAL STAGE 

DESC INTEGRATION S3_INT ; 

CREATE OR ALTER FILE FORMAT my_csv_format
  TYPE = CSV
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1 ;

CREATE OR REPLACE STAGE CUSTOMER_DATA
URL = 's3://sairamkanamarlapudi/Customers_Data.csv'
STORAGE_INTEGRATION = S3_INT
DIRECTORY = (
    ENABLE = true
    AUTO_REFRESH = true
  )
FILE_FORMAT = my_csv_format;


LIST @CUSTOMER_DATA ;

SELECT * FROM DIRECTORY(@CUSTOMER_DATA)


SELECT $1,$2 FROM @CUSTOMER_DATA

SHOW STAGES ; 

DESC STAGE CUSTOMER_DATA ; 




--CREATE SNOW FALKE TABLE

CREATE OR REPLACE TABLE CUSTOMER
(
CUSTOMERID INT,
CUSTOMERNAME VARCHAR(1000),
FILE_NAME VARCHAR(1000)
)


COPY INTO CUSTOMER
FROM (SELECT $1,$2,METADATA$FILENAME FROM @CUSTOMER_DATA ) ;



SELECT * FROM CUSTOMER ;