CREATE OR REPLACE FUNCTION UDF_GETCOUNTRY(COUNTRYID VARCHAR(100))
RETURNS VARCHAR(100)
AS
$$
SELECT CASE WHEN COUNTRYID = 'IND' THEN 'IND-INDIA' ELSE 'US' END
$$



SELECT UDF_GETCOUNTRY('IND')


SHOW FUNCTIONS LIKE '%UDF_GETCOUNTRY%';

DESCRIBE FUNCTION UDF_GETCOUNTRY(STRING) ;


------SHOW FUNCTION /RESULT_SCAN---

SHOW FUNCTIONS ;

SELECT * FROM TABLE(RESULT_SCAN('01bcaca8-3201-a91d-000d-91de00040ff6')) WHERE "language" ='SQL' ;

SELECT * FROM TABLE(RESULT_SCAN('01bcaca8-3201-a91d-000d-91de00040ff6')) WHERE "name" ='UDF_GETCOUNTRY'



----CREATE SECURE FUNCTION


CREATE OR REPLACE SECURE FUNCTION SECURE_UDF_GETCOUNTRYDATA(COUNTRYID STRING)
RETURNS STRING
AS

$$

SELECT CASE WHEN COUNTRYID = 'IND' THEN 'IND-INDIA' ELSE 'US' END

$$;



SHOW FUNCTIONS LIKE '%SECURE%';


DESCRIBE FUNCTION SECURE_UDF_GETCOUNTRYDATA(STRING) ;


GRANT USAGE ON DATABASE FLIGHTDATA TO ROLE ANALYST ;
GRANT USAGE ON SCHEMA FLIGHTDATA.FLIGHTDATA TO ROLE ANALYST;
GRANT USAGE ON FUNCTION SECURE_UDF_GETCOUNTRYDATA() TO ROLE ANALYST ; 
GRANT USAGE ON FUNCTION UDF_GETCOUNTRY() TO ROLE ANALYST ;

USE ROLE ANALYST;

DESCRIBE FUNCTION SECURE_UDF_GETCOUNTRYDATA(STRING);



----------------CREATE UDTF FUNCTIONS -----------------

SELECT CUSTOMERID,CUSTOMERNAME,FILE_NAME FROM FLIGHTDATA.FLIGHTDATA.CUSTOMER 


CREATE OR REPLACE FUNCTION UDF_CUSTOMERDATA()
RETURNS TABLE(
CUSTOMERID INT,
CUSTOMERNAME STRING,
FILE_NAME STRING
)
AS

$$
SELECT CUSTOMERID,CUSTOMERNAME,FILE_NAME FROM FLIGHTDATA.FLIGHTDATA.CUSTOMER 
$$ ;


SELECT * FROM TABLE(UDF_CUSTOMERDATA()) ;





